stages:
  tested:
    - shell: bundle exec rake spec
    - shell: bundle exec rake rubocop
  packaged:
    - gem_built:
        name: released
        version: env!VERSION
  published:
    - gem_pushed:
        gem_name: released
        authorization: |
          -----BEGIN PGP MESSAGE-----
          Comment: GPGTools - http://gpgtools.org

          hQIMA2z0x64EwZScAQ/7BCl8FAhEs1s0MctkE/2qH5xP0BQLKxi2NmDBCzTUsro4
          35tzbc17DARPv6mi77hlPcJePpCZFghTAwHIDSiz4DqkLnFYLz6Qo7Zq84/ps9En
          8Qh3eg/pB1SFCz4hxRq/ZoqO0d7LORzLW4re0JIbaknvzZXwAqy3Gz9RrkJAWLhu
          B1GA/R/f5m5btMTPey376bQLtp5CDAbOGJskupUtZ+7CCm38cCjb3qmGfFsYHB4d
          SiQHHgKIkaE16eWogMUOJH0qN1MNH+7VCa4qjUEI/D4azao5Z5eG4D/cdR0lfsCb
          gOBWB7rQlhH6UEA9XFvDwVmYZJVy/gutKIyqoF+JNPtOi7QvdY+hecKgEeheaNQ2
          zUryQxIVVPW8TlnPJvSuhvM9rYNYbm3rU6pHw7OgpocWLhhuPjswmV2ove4GQL0c
          /3kZCZp4X2AFUzxCtb7dk/0lgZGWvxbRBneLdmmCVwcMzUY0aGfc9SlJa8ttOxIK
          YWfarlo3jV8+XA9GBG9uLE+XuWKmkdU8HXs6rIL830A1R8wuNldpzl7HvTRW+eTk
          Wv2pGzRpJucmwq+9nxWuCz/9AaInFi7fHzFXydyr9/SHkt1bySma7XGjcuqjwX8Q
          HkfTxK0qPfuVjbwZCOdqX+rAFrBtM3Xz7T+QHBAxxepcnYLHT9wnsX/+zjOxXFbS
          XAFDquuFvKbcjpByDVjHLtiAlXz+i5rKU0AHaZ3lQ2b/RQz8X0I6m+Cm2gGVeylU
          xJtFEd+jHpAG7K+1gosgBJfre2P19n2L0gSBKK9OuyEQrnXvizppVwEAunzl
          =gXgF
          -----END PGP MESSAGE-----
