stages:
  test:
    - shell: bundle exec rake spec
    - shell: bundle exec rake rubocop
  package:
    - gem_built: ddreleaser.gemspec
  publish:
    - gem_pushed:
        gem_file_path: ddreleaser-*.gem
        gem_name: nanoc
        authorization: n0p3z
