vars:
  version: sh!ruby -r./lib/released/version -e 'print Released::VERSION'
  rubygems_api_key: sh!ruby -e 'require "yaml"; print YAML.load_file(File.expand_path("~/.gem/credentials"))[:rubygems_api_key]'

goals:
  - shell:
      command: bundle exec rake spec
  - shell:
      command: bundle exec rake rubocop
  - gem_built:
      name: released
      version: var!version
  - git_tag_exists:
      name: var!version
      ref: HEAD
      working_dir: .
  - gem_pushed:
      name: released
      version: var!version
      authorization: var!rubygems_api_key
  - git_ref_pushed:
      ref: var!version
      remote: origin
      working_dir: .
  - github_release_exists:
      repository_name: ddfreyne/sandbox
      tag: var!version
      release_notes: |
        Initial release.
