stages:
  - name: test
    goals:
      - shell: bundle exec rake spec
      - shell: bundle exec rake rubocop
  - name: package
    goals:
      - gem_built: ddreleaser.gemspec
  - name: publish
    goals:
      - gem_pushed:
          gem_file_path: ddreleaser-*.gem
          gem_name: nanoc
          authorization: n0p3z
